/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ammr6
 */
public class Entro extends javax.swing.JFrame {
   String F_C;
    /**
     * Creates new form Entro
     */
    public Entro() {
        initComponents();
        this.setLocationRelativeTo(null);
        F_C="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("digital farm");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(212, 188, 162));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(212, 188, 162));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1040, 0, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digital_crop.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(560, 0, 520, 640);

        button1.setBackground(new java.awt.Color(51, 119, 68));
        button1.setFont(new java.awt.Font("Sakkal Majalla", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Farmer");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);
        button1.setBounds(60, 560, 150, 40);

        button2.setBackground(new java.awt.Color(51, 119, 68));
        button2.setFont(new java.awt.Font("Sakkal Majalla", 1, 18)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("Customer");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2);
        button2.setBounds(320, 560, 150, 40);

        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 119, 68));
        jLabel2.setText("It's technical farm that offer every farmer's need and helps");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 410, 530, 50);

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 119, 68));
        jLabel3.setText("You are?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 520, 120, 32);

        jLabel5.setFont(new java.awt.Font("Arabic Typesetting", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 119, 68));
        jLabel5.setText(" customers to choose the perfect farm .");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 450, 350, 50);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 520, 520, 10);

        jLabel6.setText("©2020 عمرو و نبيل ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 620, 120, 14);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_DataBase-final.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, -10, 510, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Farmland-Agriculture-Farm-Field-Cropland-1867212.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(560, 0, 520, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        F_C="farmer";
        new FarmerIntro1(F_C).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        F_C="customer";
        new FarmerIntro1(F_C).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_button2ActionPerformed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                new Entro().setVisible(true);
                }
                catch(Exception e){
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
